go:
    cgo: false
repository:
    path: github.com/peekjef72/sql_exporter
    path: .
build:
    binaries:
        - name: mssql_exporter
          path: .
    flags: -tags mssql,netgo,usergo
    static: true
    ldflags: |
      -X github.com/prometheus/common/version.Version={{.Version}}
      -X github.com/prometheus/common/version.Revision={{.Revision}}
      -X github.com/prometheus/common/version.Branch={{.Branch}}
      -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
      -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
tarball:
    prefix: .
    files:
      - LICENSE
      - README.md
      - examples/mssql_exporter.yml
      - examples/mssql_standard.collector.yml
      - examples/mssql_targets
