go:
    cgo: true
repository:
    path: github.com/peekjef72/sql_exporter
build:
    static: false
    binaries:
        - name: oracle_exporter
          path: .
    flags: |
        -tags netgo,usergo,oracle

    #-gcflags -I/usr/include/oracle/19.16/client64
    # -I /usr/include/oracle/19.16/client64
    # -L /usr/lib/oracle/19.16/client64/lib
    ldflags: |
        -L /usr/lib/oracle/19.23/client64/lib
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildDate={{date "2006-01-02T15:04:05"}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    # static: false
tarball:
    prefix: .
    files:
      - LICENSE
      - README.md
      - config
