go:
    cgo: false
repository:
    # path: github.com/peekjef72/db2_exporter
    path: .
build:
    binaries:
        - name: oracle_exporter
          path: .
    flags: -a -tags oracle -v
    # -gcflags -I/opt/db2_exporter/lib/clidriver/include
        # -I /usr/include/oracle/19.16/client64
        # -L /usr/lib/oracle/19.16/client64/lib
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    # static: false
tarball:
    prefix: .
    files:
      - LICENSE
      - README.md
      - examples/oracle_exporter.yml
      - examples/oracle_standard.collector.yml
      - examples/targets
