{
 "title": "Oracle Transfers RAC",
 "description": "oracledb dashboard",
 "tags": [
  "Oracle",
  "db"
 ],
 "time": { "from": "2024-10-24T22:00:00.000Z", "to": "2024-10-25T04:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "dbhost",
    "label": "Server",
    "query": "label_values(oracledb_up, dbhost)"
   },
   {
    "name": "dbinstance",
    "label": "Instance",
    "query": "label_values(oracledb_up{dbhost=~\"$dbhost\"}, dbinstance)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(oracledb_up{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\"}, database)"
   }
  ]
 },
 "panels": [
  {
   "title": "Wait Events $dbinstance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "repeat": "dbinstance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(oracledb_waitclass{dbinstance=~'$dbinstance',database=~\"$database\"}) without (job)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Interconnect  Block Transfer $dbinstance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "repeat": "dbinstance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(oracledb_interconnect{dbinstance=~\"$dbinstance\", database=~\"$database\"}[5m])) without (job)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Physical Throughput $dbinstance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "repeat": "dbinstance",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(oracledb_sysmetric{dbinstance=~\"$dbinstance\", database=~\"$database\", type=~\".*bytes.*\"}) without (job)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Physical IOPs $dbinstance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "repeat": "dbinstance",
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg(oracledb_sysmetric{dbinstance=~\"$dbinstance\", database=~\"$database\", type=~\".*requests.*\"}) without (job)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}