{
 "title": "Oracle Overview",
 "description": "oracledb dashboard",
 "tags": [
  "Oracle",
  "db"
 ],
 "time": { "from": "2024-10-25T07:24:37.153Z", "to": "2024-10-25T19:24:37.153Z" },
 "templating": {
  "list": [
   {
    "name": "dbhost",
    "label": "server",
    "query": {
     "query": "label_values(up{ job=~\"oracle.*\"},  dbhost)"
    }
   },
   {
    "name": "dbinstance",
    "label": "Instance",
    "query": {
     "query": "label_values(oracledb_up{dbhost=~\"$dbhost\"}, dbinstance)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(oracledb_up{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\"}, database)"
    }
   },
   {
    "name": "short_database",
    "label": "Database",
    "query": {
     "query": "label_values(oracledb_up{ dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=\"$database\"},database)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Settings $short_database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_up{dbhost=~\"$dbhost\", dbinstance=\"$dbinstance\", database=~\"$database\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_uptime{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_custom_max_process{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}"
    }
   ]
  },
  {
   "title": "dbhost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_custom_version{ dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}\r\nor\r\noracledb_version{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}"
    }
   ]
  },
  {
   "title": "Environment",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_custom_version{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", dbinstance=~\"$dbinstance\", database=~\"$database\"}\r\nor\r\noracledb_version{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}"
    }
   ]
  },
  {
   "title": "Platform",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_custom_version{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}\r\nor\r\noracledb_version{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_custom_version{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}\r\nor\r\noracledb_version{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "process count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_process_num{ dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}\r\n"
    }
   ]
  },
  {
   "title": "cpu count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_db_system{ dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\", name=\"cpu_count\"}\r\n"
    }
   ]
  },
  {
   "title": "SGA Max size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_db_system{ dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\", name=\"sga_max_size\"}\r\n"
    }
   ]
  },
  {
   "title": "PGA Aggregate limit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_db_system{ dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\", name=\"pga_aggregate_limit\"}\r\n"
    }
   ]
  },
  {
   "title": "Sessions $short_database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "% Used Sessions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(oracledb_session{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}) * 100) / (avg(oracledb_custom_max_process{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}))",
     "legendFormat": "{{state}} {{type}}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(oracledb_session{ dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}) without (job)",
     "legendFormat": "{{state}} {{type}}"
    }
   ]
  },
  {
   "title": "Cache Hits $short_database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(oracledb_cachehitratio{dbhost=\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\", type!=\"cursor_cache_hit_ratio\", type!=\"Cursor Cache Hit Ratio\"}) without (job)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cursor Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "repeat": "dbinstance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(oracledb_cachehitratio{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\",type=~'(cursor_cache_hit_ratio)|(Cursor Cache Hit Ratio)'}) without (job)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "User Commits / Rollbacks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 234 },
   "repeat": "dbinstance",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(oracledb_sysstat{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\", type=~\".*((commit)|(rollback)).*\"}[10m])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Wait Events $short_database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 414 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Wait Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 415 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(oracledb_waitclass{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}) without (instance,database,job)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Redo Log $short_database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 422 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Redolog Switches in Last 5 min",
   "type": "bargauge",
   "description": "Redo log switches over last 5 min (v$log_history)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 423 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(oracledb_redo{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\"})"
    }
   ]
  },
  {
   "title": "Redo Log switch",
   "type": "timeseries",
   "description": "Redo log switches over last 5 min (v$log_history)",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 423 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oracledb_redo{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}",
     "legendFormat": "redo {{ database }}"
    }
   ]
  },
  {
   "title": "Execute / parse count $short_database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 429 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Executions / Parses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 430 },
   "repeat": "dbinstance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(oracledb_sysstat{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\", type=~\".*count.*\"}[10m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "FRA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 670 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "FRA Used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "avg(oracledb_recovery{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\",type=\"percent_space_used\"})"
      }
     ]
    },
    {
     "title": "FRA Reclaimable",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(oracledb_recovery{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\",type=\"percent_space_reclaimable\"})"
      }
     ]
    },
    {
     "title": "FRA Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(oracledb_recovery{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\",type=\"percent_space_used\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg(oracledb_recovery{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\",type=\"percent_space_reclaimable\"})",
       "legendFormat": "Reclaimable"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics $short_database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 671 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sessions $dbinstance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 672 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(oracledb_session{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}) without (job)",
     "legendFormat": "{{state}} {{type}}"
    }
   ]
  },
  {
   "title": "Executions Per Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 680 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "oracledb_custom_exec_tnx{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}"
    }
   ]
  },
  {
   "title": "Transactions Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 680 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "oracledb_custom_tnx_persec{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 688 },
   "repeat": "dbinstance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(oracledb_cachehitratio{ dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\", type!=\"cursor_cache_hit_ratio\" , type!=\"Cursor Cache Hit Ratio\"}) without (job)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Sort Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 898 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "oracledb_custom_sort_disk{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}",
     "legendFormat": "sort disk op"
    },
    {
     "expr": "rate(oracledb_custom_sort_disk{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}[5m])",
     "legendFormat": "sort disk op/s"
    }
   ]
  },
  {
   "title": "Sort Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 898 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "oracledb_custom_sort_memory{ dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}",
     "legendFormat": "sort memory op"
    },
    {
     "expr": "rate(oracledb_custom_sort_memory{ dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}[5m])",
     "legendFormat": "sort memory op/s"
    }
   ]
  },
  {
   "title": "Execute to Parse %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 906 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "oracledb_custom_exec_parse{ dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}"
    }
   ]
  },
  {
   "title": "Wait Event log file sync (Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 906 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "oracledb_custom_log_file{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}"
    }
   ]
  },
  {
   "title": "Wait Event db file scattered read (Average)",
   "type": "timeseries",
   "description": "Durée moyenne d'attente de l'événement (en centieme de seconde)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 914 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "targets": [
    {
     "expr": "oracledb_custom_scat_read{ dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}"
    }
   ]
  },
  {
   "title": "Soft Parse %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 914 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "oracledb_custom_soft_parse{ dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}"
    }
   ]
  },
  {
   "title": "Wait Event db file sequential read (Total Wait)",
   "type": "timeseries",
   "description": "Somme des evenements d'attente type sequential read",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 922 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "oracledb_custom_seq_read{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}",
     "legendFormat": "total number"
    },
    {
     "expr": "rate(oracledb_custom_seq_read{ dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}[5m])",
     "legendFormat": "count/s"
    }
   ]
  },
  {
   "title": "Wait Event control file sequential read (Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 922 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "targets": [
    {
     "expr": "oracledb_custom_cont_read{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}"
    }
   ]
  },
  {
   "title": "Latch free foreground",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 930 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oracledb_custom_latch_free{ dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}"
    }
   ]
  },
  {
   "title": "Free buffer requested total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 930 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oracledb_custom_free_buffer{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}"
    }
   ]
  },
  {
   "title": "Row lock contention",
   "type": "stat",
   "description": "Nombre de row lock contention",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 938 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "oracledb_custom_lock_contention{dbhost=~\"$dbhost\", dbinstance=~\"$dbinstance\", database=~\"$database\"}\n"
    }
   ]
  }
 ]
}