#--------- Start prometheus db2 exporter  ---------#
  - job_name: "db2"
    metrics_path: /metrics
    file_sd_configs:
      - files: [ "/etc/prometheus/db2_nodes/*.yml" ]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      # use the value set in __tmp_exporter_host as exporter host name
      - source_labels: [__tmp_exporter_host]
        target_label: __address__
      # or directly:
      # - target_label: __address__
      #   replacement: "db2_exporter_host.domain.name:9165"  # The db2_exporter's real hostname.

#--------- End prometheus db2 exporter ---------#
