{
 "title": "SAP HANA DB",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "segment",
    "query": {
     "query": "label_values(up{job=~\"hanasql.*\"},segment)"
    }
   },
   {
    "name": "environment",
    "query": {
     "query": "label_values(up{segment=~\"$segment\", job=~\"hanasql.*\"},environment)"
    }
   },
   {
    "name": "host",
    "label": "server",
    "query": {
     "query": "label_values(up{segment=~\"$segment\", environment=~\"$environment\", job=~\"hanasql.*\"},host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DB Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hanasql_up{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tenant Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hanasql_status{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hanasql_up{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hanasql_uptime{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hanasql_uptime{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime Date",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(time() - hanasql_uptime{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"})*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hanasql_blocked_transactions{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Table Locks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hanasql_table_locks{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "hanasql_connection_active{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "{{ service }} Active"
    }
   ]
  },
  {
   "title": "Connection by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "hanasql_connection_type{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "{{service }} {{ type }}"
    }
   ]
  },
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Backup Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (host, environment, type) (hanasql_backup_status{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host, environment, type) (hanasql_backup_timestamp{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host, environment, type) (hanasql_backup_count{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host, environment, type) (hanasql_backup_oldest{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup State History",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "hanasql_backup_status{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  { "title": "Schemas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Tables Disk occupation by schema",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "hanasql_schema_tables_disk_used_bytes{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "{{ schema_name }}"
    }
   ]
  },
  {
   "title": "Tables Pages Count by schema",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hanasql_schema_tables_page_count{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "{{ schema_name }}"
    }
   ]
  },
  {
   "title": "Bytes Read/Write/Append by schema",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hanasql_schema_tables_bytes_write{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "{{ schema_name }} write"
    },
    {
     "expr": "hanasql_schema_tables_bytes_read{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "{{ schema_name }} read"
    },
    {
     "expr": "hanasql_schema_tables_bytes_append{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "{{ schema_name }} append"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Heap Memory by services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "hanasql_service_memory_heaps_used_size_bytes{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"} / hanasql_service_memory_heaps_allocated_size_bytes{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "{{ service_name }} size"
    }
   ]
  },
  {
   "title": "Pyhical Memory by services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "hanasql_service_memory_physical_used_bytes{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "{{ service_name }}"
    },
    {
     "expr": "hanasql_service_memory_total_used_bytes{segment=~\"$segment\", environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "{{ service_name }} total"
    }
   ]
  }
 ]
}